name: amazing_colors
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.8
  solid_lints: ^0.3.3

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_native_splash:
  image: "assets/images/splashScreen.png"
  color: "#2B2E31"
  android: true
  ios: true
  android_12:
    image: "assets/images/android_12_splash.png"
    color: "#2B2E31"

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne/CarterOne-Regular.ttf
          weight: 400